apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-db-mongodata
  name: user-db-mongodata
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-db
  name: user-db
  namespace: production
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      annotations:
        sidecar.istio.io/inject: "false"
        dynatrace/instrument: "false"
        pipeline.stage: prod-stable
        pipeline.build: 2.0.2.1234
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        io.kompose.service: user-db
        name: user-db
        stage: prod
        version: "2.0"
        tier: data
        product: sockshop
    spec:
      containers:
      - image: mongo
        name: user-db
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: "password"
        - name: MONGODB_USER
          value: "user"
        - name: MONGODB_PASSWORD
          value: "password"
        - name: MONGODB_DATABASE
          value: "default"
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: user-db-mongodata
      restartPolicy: Always
      volumes:
      - name: user-db-mongodata
        persistentVolumeClaim:
          claimName: user-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-db
  name: user-db
  namespace: production
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: user-db
status:
  loadBalancer: {}